---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность просматривать товары и получать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
non-functional:
  - Сайт нужно разработать с учетом удобства использования.
  - Сайт должен быть оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
implicit:
  - Пользовательская навигация должна быть интуитивной.
  - Интерфейс должен быть простым и понятным для широкого круга пользователей.
  - Оптимизация для скорости работы подразумевает не только быстрый поиск товаров, но и быструю загрузку страниц и обработку действий пользователя.
  - Сайт должен корректно отображаться и функционировать на различных устройствах и разных браузерах без потери функциональности.
  - Возможность обработки большого объема трафика предполагает, что архитектура сайта должна быть масштабируемой, чтобы обеспечивать стабильную работу даже при увеличении посещаемости.
  - Сайт должен быть доступен для пользователей с ограниченными возможностями, что подразумевает соответствие стандартам доступности - (WCAG).
